//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_dict_tbsalesman
    {
        public string code { get; set; }
        public string name { get; set; }
        public string sex { get; set; }
        public string default_task { get; set; }
        public string roles { get; set; }
        public string password { get; set; }
        public string if_valid { get; set; }
        public string remark { get; set; }
        public string ref_code { get; set; }
        public string pycode { get; set; }
    }
}
