//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_dict_tbinterface
    {
        public string intf_dept { get; set; }
        public string dept_name { get; set; }
        public string intf_type { get; set; }
        public Nullable<bool> is_active { get; set; }
    }
}
