//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_dict_tbhtestcode
    {
        public string code { get; set; }
        public string name { get; set; }
        public string code_index { get; set; }
        public string ifdel { get; set; }
    }
}
