//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_dict_manager
    {
        public string dict_code { get; set; }
        public string dict_code_short { get; set; }
        public string dict_caption { get; set; }
        public int dict_order_seq { get; set; }
        public string dict_sign_sql_1 { get; set; }
        public string dict_sign_sql_2 { get; set; }
        public string dict_load_sql { get; set; }
        public decimal dict_signature { get; set; }
        public string dict_client_ctlname { get; set; }
        public bool dict_if_valid { get; set; }
        public Nullable<System.DateTime> dict_update_time { get; set; }
        public string dict_desc { get; set; }
    }
}
