//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_dict_tbcode
    {
        public int identkey { get; set; }
        public string categoryid { get; set; }
        public string categorydesc { get; set; }
        public string codeid { get; set; }
        public string codename { get; set; }
        public string pcodeid { get; set; }
        public string variablename { get; set; }
        public Nullable<int> hothits { get; set; }
        public string ifsys { get; set; }
        public string ifdel { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> seq { get; set; }
    }
}
