//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_dict_tbdiscountRates
    {
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<decimal> default_rate { get; set; }
        public string roles { get; set; }
        public string if_forSettle { get; set; }
        public string if_standard { get; set; }
        public string if_valid { get; set; }
        public string remark { get; set; }
        public string if_allowCustom { get; set; }
    }
}
