//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_sdsl_StatResult
    {
        public Nullable<int> seq { get; set; }
        public string testname { get; set; }
        public string testdownlimit { get; set; }
        public string testuplimit { get; set; }
        public string testrange { get; set; }
        public System.DateTime checkdate { get; set; }
        public string testresult { get; set; }
        public string teststatus { get; set; }
        public string testsign { get; set; }
    }
}
