//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_sdsl_statTest
    {
        public string testcode { get; set; }
        public string testname { get; set; }
        public string ifcheck { get; set; }
        public string testorder { get; set; }
    }
}
