//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class discountRates_task_union
    {
        public string taskcode { get; set; }
        public string unionCode { get; set; }
        public string discount_type { get; set; }
        public Nullable<decimal> discount_rate { get; set; }
        public string if_taskrate { get; set; }
    }
}
