//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hactrep
    {
        public string membcode { get; set; }
        public string checkcode { get; set; }
        public string tjyear { get; set; }
        public Nullable<System.DateTime> checkdate { get; set; }
        public string his { get; set; }
        public string checkdoc { get; set; }
        public string hresult { get; set; }
        public string hresultother { get; set; }
    }
}
