//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hactdepdiag
    {
        public string checkcode { get; set; }
        public string deptcode { get; set; }
        public string membcode { get; set; }
        public string checkdoc { get; set; }
        public string htestcode { get; set; }
        public string signcode { get; set; }
        public string signtype { get; set; }
        public string signstatus { get; set; }
        public string diagname { get; set; }
        public string ifnewsign { get; set; }
        public string ifimpt { get; set; }
        public string ifdoubt { get; set; }
    }
}
