//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hactmemb
    {
        public Nullable<short> ifdel { get; set; }
        public Nullable<short> ifact { get; set; }
        public string actstr { get; set; }
        public string membcode { get; set; }
        public string a0101 { get; set; }
        public string a0107 { get; set; }
        public string age { get; set; }
        public Nullable<System.DateTime> checkdate { get; set; }
    }
}
