//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hactdepdiag
    {
        public string checkcode { get; set; }
        public string deptcode { get; set; }
        public string membcode { get; set; }
        public string checkdoc { get; set; }
        public string htestcode { get; set; }
        public string signcode { get; set; }
        public string signtype { get; set; }
        public string signstatus { get; set; }
        public string diagname { get; set; }
        public string ifnewsign { get; set; }
        public string ifimpt { get; set; }
        public string ifdoubt { get; set; }
    }
}
