//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hactrep
    {
        public string membcode { get; set; }
        public string checkcode { get; set; }
        public string tjyear { get; set; }
        public Nullable<System.DateTime> checkdate { get; set; }
        public string his { get; set; }
        public string checkdoc { get; set; }
        public string hresult { get; set; }
        public string hresultother { get; set; }
    }
}
