//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class haudit
    {
        public string adobj { get; set; }
        public string adcode { get; set; }
        public string adseq { get; set; }
        public string adclass { get; set; }
        public string adevent { get; set; }
        public Nullable<short> adlevel { get; set; }
        public string adresult { get; set; }
        public string adrefdata { get; set; }
        public string adpc { get; set; }
        public string adip { get; set; }
        public string adoper { get; set; }
        public Nullable<System.DateTime> adtime { get; set; }
        public Nullable<short> ifdel { get; set; }
        public string verkey { get; set; }
    }
}
