//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class haudit
    {
        public string adobj { get; set; }
        public string adcode { get; set; }
        public string adclass { get; set; }
        public short adseq { get; set; }
        public string adevent { get; set; }
        public Nullable<short> adlevel { get; set; }
        public string adresult { get; set; }
        public string adpc { get; set; }
        public string adip { get; set; }
        public string adoper { get; set; }
        public Nullable<System.DateTime> adtime { get; set; }
        public Nullable<short> ifdel { get; set; }
        public string verkey { get; set; }
    }
}
