//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hbasegrpedit
    {
        public string b0110 { get; set; }
        public System.DateTime updateday { get; set; }
        public string b0105 { get; set; }
        public string editreason { get; set; }
        public string editnote { get; set; }
        public string oper { get; set; }
    }
}
