//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hbasemembdiag
    {
        public string gb2260 { get; set; }
        public string membcode { get; set; }
        public string signcode { get; set; }
        public string signtype { get; set; }
        public string diagwhere { get; set; }
        public string diagdegree { get; set; }
        public string diagclass { get; set; }
        public string diagname { get; set; }
        public string diagviewform { get; set; }
        public string ifnewsign { get; set; }
        public string signstatus { get; set; }
        public string diagdeptcode { get; set; }
        public string htestcode { get; set; }
        public string his { get; set; }
        public string tjyear { get; set; }
        public string checkcode { get; set; }
        public string remark { get; set; }
        public string ifactive { get; set; }
        public string ifcipher { get; set; }
        public string note { get; set; }
        public string tag { get; set; }
        public string taskcode { get; set; }
    }
}
