//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hbasemembdiag
    {
        public string gb2260 { get; set; }
        public string membcode { get; set; }
        public string signcode { get; set; }
        public string signtype { get; set; }
        public string diagwhere { get; set; }
        public string diagdegree { get; set; }
        public string diagclass { get; set; }
        public string diagname { get; set; }
        public string diagviewform { get; set; }
        public string ifnewsign { get; set; }
        public string signstatus { get; set; }
        public string diagdeptcode { get; set; }
        public string htestcode { get; set; }
        public string his { get; set; }
        public string tjyear { get; set; }
        public string checkcode { get; set; }
        public string remark { get; set; }
        public string ifactive { get; set; }
        public string ifcipher { get; set; }
        public string note { get; set; }
        public string tag { get; set; }
        public string taskcode { get; set; }
    }
}
