//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hbasememb
    {
        public int identkey { get; set; }
        public string gb2260 { get; set; }
        public string ifdel { get; set; }
        public string iftag { get; set; }
        public string membcode { get; set; }
        public string membtype { get; set; }
        public string membclasscode { get; set; }
        public string a0741 { get; set; }
        public string medicareno { get; set; }
        public string medipcno { get; set; }
        public string a0177 { get; set; }
        public string a0101 { get; set; }
        public string a0101x { get; set; }
        public string pycode { get; set; }
        public string a0107 { get; set; }
        public Nullable<System.DateTime> a0111 { get; set; }
        public string a0121 { get; set; }
        public string a0114 { get; set; }
        public string a0405 { get; set; }
        public string a2205 { get; set; }
        public string a0704 { get; set; }
        public Nullable<System.DateTime> a0707 { get; set; }
        public string a0724 { get; set; }
        public string a6405 { get; set; }
        public Nullable<System.DateTime> a6410 { get; set; }
        public string a0127 { get; set; }
        public string mobileno { get; set; }
        public string a8210 { get; set; }
        public string a8215 { get; set; }
        public string a8205 { get; set; }
        public string a8205a { get; set; }
        public string email { get; set; }
        public string workunit { get; set; }
        public string b0110 { get; set; }
        public Nullable<System.DateTime> initday { get; set; }
        public string initoper { get; set; }
        public Nullable<System.DateTime> updateday { get; set; }
        public string updateoper { get; set; }
        public string cancelcode { get; set; }
        public Nullable<System.DateTime> cancelday { get; set; }
        public Nullable<System.DateTime> checkdate { get; set; }
        public string taskcode { get; set; }
        public string checkcode { get; set; }
        public byte[] membphoto { get; set; }
        public string diaghome { get; set; }
        public string diagdrug { get; set; }
        public string diagout { get; set; }
        public string diagoper { get; set; }
        public string diagnow { get; set; }
        public string remark { get; set; }
        public string a0721 { get; set; }
        public string a1005 { get; set; }
        public Nullable<System.DateTime> a0141 { get; set; }
        public string diagblood { get; set; }
        public string tag { get; set; }
        public string hiscode { get; set; }
        public string accsource { get; set; }
        public string accpwd { get; set; }
        public string accquestion { get; set; }
        public string accanswer { get; set; }
        public string ifemail { get; set; }
        public string ifsms { get; set; }
        public string ifquery { get; set; }
        public Nullable<System.DateTime> lastquerydate { get; set; }
        public Nullable<int> querycount { get; set; }
        public string duty { get; set; }
        public string healthcode { get; set; }
        public string feemode { get; set; }
        public string tasktype { get; set; }
        public string ifconfirm { get; set; }
        public Nullable<System.DateTime> confirmdate { get; set; }
        public Nullable<short> mytag { get; set; }
        public int statusflag { get; set; }
        public string photoindex { get; set; }
    }
}
