//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hbasegrp
    {
        public string gb2260 { get; set; }
        public string b0110 { get; set; }
        public string ifdel { get; set; }
        public string b0105 { get; set; }
        public string pycode { get; set; }
        public string membtype { get; set; }
        public string b0160 { get; set; }
        public string b0150 { get; set; }
        public string b0170 { get; set; }
        public string b0120 { get; set; }
        public string B0120A { get; set; }
        public string district { get; set; }
        public string filecode { get; set; }
        public string b0115 { get; set; }
        public string mailbox { get; set; }
        public string b0125 { get; set; }
        public string b0125A { get; set; }
        public string b0130 { get; set; }
        public string email { get; set; }
        public string webname { get; set; }
        public string linkman { get; set; }
        public Nullable<int> b0710 { get; set; }
        public Nullable<int> b3205 { get; set; }
        public Nullable<int> b3210 { get; set; }
        public Nullable<System.DateTime> initday { get; set; }
        public string initoper { get; set; }
        public Nullable<System.DateTime> updateday { get; set; }
        public string updateoper { get; set; }
        public string remark { get; set; }
        public int identkey { get; set; }
        public string medicareno { get; set; }
        public string b0110x { get; set; }
        public string accsource { get; set; }
        public string managerid { get; set; }
        public string grpcode { get; set; }
        public Nullable<int> qty_Class1 { get; set; }
        public Nullable<int> qty_Class2 { get; set; }
        public Nullable<int> qty_Class3 { get; set; }
        public Nullable<int> tag { get; set; }
        public string ifconfirm { get; set; }
        public Nullable<System.DateTime> confirmdate { get; set; }
        public string bzoper { get; set; }
        public string bztel { get; set; }
        public string bzaddr { get; set; }
        public string bznote { get; set; }
        public string linkman2 { get; set; }
        public string linkman2_email { get; set; }
        public string linkman2_mobile { get; set; }
        public string linkman2_phone { get; set; }
        public string linkman2_qq { get; set; }
        public string linkman2_remark { get; set; }
        public string linkman_mobile { get; set; }
        public string linkman_phone { get; set; }
        public string linkman_qq { get; set; }
        public string linkman_remark { get; set; }
        public Nullable<int> qty_a6405 { get; set; }
    }
}
