//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcheckmemb
    {
        public string checkcode { get; set; }
        public string ifdel { get; set; }
        public string taskcode { get; set; }
        public string taskseq { get; set; }
        public string seq { get; set; }
        public string ifprinted { get; set; }
        public string checkstatus { get; set; }
        public string iffinished { get; set; }
        public string b0110 { get; set; }
        public string b0105 { get; set; }
        public string b0160 { get; set; }
        public string membcode { get; set; }
        public string membtype { get; set; }
        public string a0101 { get; set; }
        public string a0107 { get; set; }
        public string age { get; set; }
        public string a6405 { get; set; }
        public string a0704 { get; set; }
        public Nullable<System.DateTime> checkdate { get; set; }
        public string asmcode { get; set; }
        public string asmseq { get; set; }
        public string asmname { get; set; }
        public string ifasmdep { get; set; }
        public string asmdepstr { get; set; }
        public Nullable<decimal> checkfee { get; set; }
        public string ifplus { get; set; }
        public Nullable<decimal> checkfeeplus { get; set; }
        public string remark { get; set; }
        public string tele { get; set; }
        public string email { get; set; }
        public string accesscode { get; set; }
        public string sendwayid { get; set; }
        public string ifsend { get; set; }
        public Nullable<decimal> feesum { get; set; }
        public string ifcard { get; set; }
        public string workunit { get; set; }
        public Nullable<decimal> undofee { get; set; }
        public Nullable<decimal> discountfee { get; set; }
        public string pis_01 { get; set; }
        public Nullable<short> bseq { get; set; }
        public Nullable<short> ifad { get; set; }
        public string adclass { get; set; }
        public string tasktype { get; set; }
        public string feemode { get; set; }
        public string priunionchg { get; set; }
    }
}
