//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hdatadepunion
    {
        public string gb2260 { get; set; }
        public string checkcode { get; set; }
        public string deptcode { get; set; }
        public string unioncode { get; set; }
        public string taskcode { get; set; }
        public string seq { get; set; }
        public string membcode { get; set; }
        public string membtype { get; set; }
        public Nullable<System.DateTime> initday { get; set; }
        public string checkstatus { get; set; }
        public string sampleno { get; set; }
        public string depresult { get; set; }
        public Nullable<System.DateTime> checkdate { get; set; }
        public string checkdoc { get; set; }
        public string reviewdoc { get; set; }
        public string iffinished { get; set; }
        public string iflock { get; set; }
        public string ifdata { get; set; }
        public string testsignstr { get; set; }
        public Nullable<decimal> unionfee { get; set; }
        public string ifplus { get; set; }
        public string tag { get; set; }
        public string ifsettle { get; set; }
        public string rackno { get; set; }
        public string rackoper { get; set; }
        public string racktime { get; set; }
        public string uname { get; set; }
        public short deptseq { get; set; }
        public string work { get; set; }
        public Nullable<short> rackbatch { get; set; }
        public string uniondesc { get; set; }
        public Nullable<short> regstatus { get; set; }
        public string checklevel { get; set; }
        public string settlecode { get; set; }
        public Nullable<short> unionExchangeGroup { get; set; }
    }
}
