//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hdatadepdiag
    {
        public string gb2260 { get; set; }
        public string checkcode { get; set; }
        public Nullable<int> identkeyno { get; set; }
        public string deptcode { get; set; }
        public string unioncode { get; set; }
        public string taskcode { get; set; }
        public string membcode { get; set; }
        public string ifdel { get; set; }
        public string iftag { get; set; }
        public string ifnewsign { get; set; }
        public string ifwhy { get; set; }
        public string signtype { get; set; }
        public string signcode { get; set; }
        public string signclass { get; set; }
        public string signstatus { get; set; }
        public string diagdeptcode { get; set; }
        public string seq { get; set; }
        public string htestcode { get; set; }
        public string diagwhere { get; set; }
        public string diagdegree { get; set; }
        public string diagclass { get; set; }
        public string stdcode { get; set; }
        public string diagcode { get; set; }
        public string mcode { get; set; }
        public string diagname { get; set; }
        public string diagviewform { get; set; }
        public Nullable<System.DateTime> checkdate { get; set; }
        public string checkdoc { get; set; }
        public string testinfoch { get; set; }
        public string diaginfoch { get; set; }
        public string remark { get; set; }
        public string tag { get; set; }
        public string ifguide { get; set; }
        public string ifimpt { get; set; }
        public string ifdoubt { get; set; }
    
        public virtual hlibdiag hlibdiag { get; set; }
    }
}
