//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hdataimg
    {
        public string taskcode { get; set; }
        public string membcode { get; set; }
        public Nullable<System.DateTime> checkdate { get; set; }
        public string checkcode { get; set; }
        public string imgType { get; set; }
        public string imgSeq { get; set; }
        public string imgFilePath { get; set; }
        public string checkPart { get; set; }
        public string checkDesc { get; set; }
        public string checkDoc { get; set; }
        public string OperNurse { get; set; }
        public string sampleNo { get; set; }
        public string deviceName { get; set; }
        public string tag1 { get; set; }
        public string tag2 { get; set; }
        public string deptcode { get; set; }
    }
}
