//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hdataimg
    {
        public string taskcode { get; set; }
        public string membcode { get; set; }
        public Nullable<System.DateTime> checkdate { get; set; }
        public string checkcode { get; set; }
        public string imgType { get; set; }
        public string imgSeq { get; set; }
        public string imgFilePath { get; set; }
        public string checkPart { get; set; }
        public string checkDesc { get; set; }
        public string checkDoc { get; set; }
        public string OperNurse { get; set; }
        public string sampleNo { get; set; }
        public string deviceName { get; set; }
        public string tag1 { get; set; }
        public string tag2 { get; set; }
        public string deptcode { get; set; }
    }
}
