//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hknowtest
    {
        public string testcode { get; set; }
        public string wayid { get; set; }
        public string testsign { get; set; }
        public string ifdel { get; set; }
        public string seq { get; set; }
        public int identkey { get; set; }
        public string signcode { get; set; }
        public string diagname { get; set; }
        public string sysid { get; set; }
        public string sysver { get; set; }
    }
}
