//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hknowunion
    {
        public string unioncode { get; set; }
        public string testsignstr { get; set; }
        public string ifdel { get; set; }
        public string seq { get; set; }
        public int identkey { get; set; }
        public string signcode { get; set; }
        public string diagname { get; set; }
    }
}
