//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hknowdiag
    {
        public string lev { get; set; }
        public string code { get; set; }
        public string signcode { get; set; }
        public string diagname { get; set; }
        public string seq { get; set; }
        public short matchsum { get; set; }
        public string warning { get; set; }
    }
}
