//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlibtestdict
    {
        public string testcode { get; set; }
        public string seq { get; set; }
        public string ifdel { get; set; }
        public string pycode { get; set; }
        public string wbcode { get; set; }
        public string dictname { get; set; }
        public int identkey { get; set; }
    }
}
