//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlibpisform
    {
        public string usercode { get; set; }
        public string deptcode { get; set; }
        public int deptseq { get; set; }
        public string testcode { get; set; }
        public int testseq { get; set; }
        public string testresult { get; set; }
        public string keysign { get; set; }
        public Nullable<short> ifdefa { get; set; }
        public string oper { get; set; }
        public Nullable<System.DateTime> operdate { get; set; }
    }
}
