//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlibpis
    {
        public string usercode { get; set; }
        public string deptcode { get; set; }
        public int deptseq { get; set; }
        public string htestcode { get; set; }
        public string signcode { get; set; }
        public string signname { get; set; }
        public string signadvice { get; set; }
        public string pycode { get; set; }
        public int signusage { get; set; }
        public int ifdetail { get; set; }
        public string his { get; set; }
        public string oper { get; set; }
        public Nullable<System.DateTime> operdate { get; set; }
    
        public virtual hlibdiag hlibdiag { get; set; }
    }
}
