//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlibdiag
    {
        public hlibdiag()
        {
            this.hdatadepdiag = new HashSet<hdatadepdiag>();
        }
    
        public string diagdeptcode { get; set; }
        public string seq { get; set; }
        public string htestcode { get; set; }
        public string htestname { get; set; }
        public string usagecode { get; set; }
        public string signcode { get; set; }
        public string signtype { get; set; }
        public string ifdel { get; set; }
        public string stdcode { get; set; }
        public string diagcode { get; set; }
        public string mcode { get; set; }
        public string diagname { get; set; }
        public string diagnameclx { get; set; }
        public string diagnameoth { get; set; }
        public string diagnamestd { get; set; }
        public string diagnamestde { get; set; }
        public string diagwhere { get; set; }
        public string diagdegree { get; set; }
        public string diagclass { get; set; }
        public string diagviewform { get; set; }
        public string pycode { get; set; }
        public string wbcode { get; set; }
        public string diaginfoch { get; set; }
        public string diaginfoen { get; set; }
        public string diagadvshort { get; set; }
        public string diagadvlong { get; set; }
        public string diagguide { get; set; }
        public string diagpost { get; set; }
        public string tag { get; set; }
        public string postcode { get; set; }
        public string statcsyscode { get; set; }
        public string statsigncode { get; set; }
        public string docdept { get; set; }
        public string checkdoc { get; set; }
        public Nullable<System.DateTime> updateday { get; set; }
        public string remark { get; set; }
        public string ifsend { get; set; }
        public string ifhide { get; set; }
        public string senddept { get; set; }
        public int identkey { get; set; }
        public string diagdept { get; set; }
        public string sysid { get; set; }
        public string sexsign { get; set; }
        public string sysver { get; set; }
        public short statusflag { get; set; }
    
        public virtual ICollection<hdatadepdiag> hdatadepdiag { get; set; }
    }
}
