//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlibtestattr
    {
        public string testcode { get; set; }
        public string wayid { get; set; }
        public string seq { get; set; }
        public string testattr { get; set; }
        public string dataway { get; set; }
        public string atttext { get; set; }
        public string attdata { get; set; }
        public string attrnote { get; set; }
    }
}
