//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlibuniondiag
    {
        public string unioncode { get; set; }
        public string htestcode { get; set; }
        public string usagecode { get; set; }
        public string seq { get; set; }
        public string deptcode { get; set; }
        public string signcode { get; set; }
        public string signtype { get; set; }
        public string ifdel { get; set; }
        public string stdcode { get; set; }
        public string diagcode { get; set; }
        public string mcode { get; set; }
        public string diagname { get; set; }
        public string diagdeptcode { get; set; }
        public string pycode { get; set; }
        public string tag { get; set; }
        public Nullable<int> identkeyno { get; set; }
    }
}
