//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlibdept
    {
        public string deptclass { get; set; }
        public string deptcode { get; set; }
        public string ifdel { get; set; }
        public string deptname { get; set; }
        public string deptaddr { get; set; }
        public string deptnote { get; set; }
        public string deptdesc { get; set; }
        public string diagtestlist { get; set; }
        public string tag { get; set; }
    }
}
