//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlibtest
    {
        public hlibtest()
        {
            this.hdatadeptest = new HashSet<hdatadeptest>();
            this.hlibuniontest = new HashSet<hlibuniontest>();
        }
    
        public string testcode { get; set; }
        public string wayid { get; set; }
        public string waydictname { get; set; }
        public string seq { get; set; }
        public string tshort { get; set; }
        public string testcname { get; set; }
        public string testename { get; set; }
        public string testunit { get; set; }
        public string idrange { get; set; }
        public string testdownlimit { get; set; }
        public string testuplimit { get; set; }
        public string testrange { get; set; }
        public string testsupperlimit { get; set; }
        public string testmdownlimit { get; set; }
        public string testmuplimit { get; set; }
        public string testmrange { get; set; }
        public string testfdownlimit { get; set; }
        public string testfuplimit { get; set; }
        public string testfrange { get; set; }
        public string idsex { get; set; }
        public string idattr { get; set; }
        public string ifdefa { get; set; }
        public string defatext { get; set; }
        public string htreeid { get; set; }
        public string htreedictname { get; set; }
        public string htestcode { get; set; }
        public string htestdictname { get; set; }
        public Nullable<System.DateTime> updateday { get; set; }
        public string updateoper { get; set; }
        public string sysid { get; set; }
        public string signprint { get; set; }
        public string xtestcode { get; set; }
        public string anatcode { get; set; }
        public string othname { get; set; }
        public string purpose { get; set; }
        public string remark { get; set; }
        public string ifbrief { get; set; }
        public Nullable<short> testclass { get; set; }
        public Nullable<int> testorder { get; set; }
        public string sysver { get; set; }
        public short statusflag { get; set; }
    
        public virtual ICollection<hdatadeptest> hdatadeptest { get; set; }
        public virtual ICollection<hlibuniontest> hlibuniontest { get; set; }
    }
}
