//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlibuniondiag
    {
        public string unioncode { get; set; }
        public string htestcode { get; set; }
        public string usagecode { get; set; }
        public string seq { get; set; }
        public string deptcode { get; set; }
        public string signcode { get; set; }
        public string signtype { get; set; }
        public string ifdel { get; set; }
        public string stdcode { get; set; }
        public string diagcode { get; set; }
        public string mcode { get; set; }
        public string diagname { get; set; }
        public string diagdeptcode { get; set; }
        public string pycode { get; set; }
        public string tag { get; set; }
        public Nullable<int> identkeyno { get; set; }
    }
}
