//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlibrepform
    {
        public string gb2260 { get; set; }
        public string repcode { get; set; }
        public string seq { get; set; }
        public string remark { get; set; }
        public string rolecode { get; set; }
        public string ifdel { get; set; }
        public byte[] repform { get; set; }
        public Nullable<System.DateTime> updateday { get; set; }
        public string updateoper { get; set; }
        public string filename { get; set; }
        public string sysid { get; set; }
        public string sysver { get; set; }
        public string note { get; set; }
    }
}
