//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlibtestops
    {
        public string testcode { get; set; }
        public string wayid { get; set; }
        public string signcode { get; set; }
        public string diagname { get; set; }
        public string diagwhere { get; set; }
        public string diagdegree { get; set; }
        public string diagclass { get; set; }
        public string signdata { get; set; }
    }
}
