//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlibuniontest
    {
        public string unioncode { get; set; }
        public string htestcode { get; set; }
        public string testcode { get; set; }
        public string wayid { get; set; }
        public string seq { get; set; }
        public string ifdel { get; set; }
        public string deptcode { get; set; }
        public string tag { get; set; }
        public string ischeck { get; set; }
    
        public virtual hlibtest hlibtest { get; set; }
    }
}
