//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlibuniontest
    {
        public string unioncode { get; set; }
        public string htestcode { get; set; }
        public string testcode { get; set; }
        public string wayid { get; set; }
        public string seq { get; set; }
        public string ifdel { get; set; }
        public string deptcode { get; set; }
        public string tag { get; set; }
        public string ischeck { get; set; }
    
        public virtual hlibtest hlibtest { get; set; }
    }
}
