//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlibpisform
    {
        public string usercode { get; set; }
        public string deptcode { get; set; }
        public int deptseq { get; set; }
        public string testcode { get; set; }
        public int testseq { get; set; }
        public string testresult { get; set; }
        public string keysign { get; set; }
        public Nullable<short> ifdefa { get; set; }
        public string oper { get; set; }
        public Nullable<System.DateTime> operdate { get; set; }
    }
}
