//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlogdata
    {
        public long identkey { get; set; }
        public Nullable<System.DateTime> logdate { get; set; }
        public string logIP { get; set; }
        public string logmodule { get; set; }
        public string loglevel { get; set; }
        public string remark { get; set; }
        public string logoper { get; set; }
        public Nullable<int> errorcode { get; set; }
    }
}
