//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlogdata
    {
        public long identkey { get; set; }
        public Nullable<System.DateTime> logdate { get; set; }
        public string logIP { get; set; }
        public string logmodule { get; set; }
        public string loglevel { get; set; }
        public string remark { get; set; }
        public string logoper { get; set; }
        public Nullable<int> errorcode { get; set; }
        public string mac { get; set; }
        public string logtime { get; set; }
        public string logclass { get; set; }
        public string logtype { get; set; }
        public string logcode { get; set; }
    }
}
