//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hstat_sessions
    {
        public string SessUser { get; set; }
        public string SessType { get; set; }
        public string SessBand { get; set; }
        public string SessCode { get; set; }
        public string SessValue { get; set; }
    }
}
