//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hstatmainrec
    {
        public string statrec_code { get; set; }
        public string statrec_title { get; set; }
        public Nullable<System.DateTime> stat_begindate { get; set; }
        public Nullable<System.DateTime> stat_enddate { get; set; }
        public string stat_remark { get; set; }
        public Nullable<bool> printed_flag { get; set; }
        public Nullable<System.DateTime> lastprint_date { get; set; }
        public Nullable<bool> confirm_flag { get; set; }
        public Nullable<System.DateTime> confirm_date { get; set; }
        public string maindoctor { get; set; }
        public string @operator { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string history_years { get; set; }
        public Nullable<bool> rerun_flag { get; set; }
        public string rerun_desc { get; set; }
    }
}
