//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hstat_sessions
    {
        public string SessUser { get; set; }
        public string SessType { get; set; }
        public string SessBand { get; set; }
        public string SessCode { get; set; }
        public string SessValue { get; set; }
    }
}
