//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hstatmainrec
    {
        public string statrec_code { get; set; }
        public string statrec_title { get; set; }
        public Nullable<System.DateTime> stat_begindate { get; set; }
        public Nullable<System.DateTime> stat_enddate { get; set; }
        public string stat_remark { get; set; }
        public bool printed_flag { get; set; }
        public Nullable<System.DateTime> lastprint_date { get; set; }
        public bool confirm_flag { get; set; }
        public Nullable<System.DateTime> confirm_date { get; set; }
        public string maindoctor { get; set; }
        public string @operator { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string history_years { get; set; }
        public bool rerun_flag { get; set; }
        public string rerun_desc { get; set; }
    }
}
