//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hstatdata_history_defines
    {
        public string statrec_code { get; set; }
        public string stathis_code { get; set; }
        public string stathis_name { get; set; }
        public Nullable<System.DateTime> stathis_begindate { get; set; }
        public Nullable<System.DateTime> stathis_enddate { get; set; }
    }
}
