//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hstatmethods
    {
        public string statmethod_code { get; set; }
        public string method_name { get; set; }
        public short dispseq { get; set; }
        public short method_runseq { get; set; }
        public bool method_mustflag { get; set; }
        public string depend_methods { get; set; }
        public Nullable<short> method_progtype { get; set; }
        public string method_progname { get; set; }
        public bool method_invalidflag { get; set; }
        public string method_params { get; set; }
        public string method_desc { get; set; }
    }
}
