//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hstatconds
    {
        public string statcond_code { get; set; }
        public string statcond_name { get; set; }
        public string statcond_fieldname { get; set; }
        public string statcond_fieldtype { get; set; }
        public bool statcond_multflag { get; set; }
        public string statcond_desc { get; set; }
        public bool statcond_common_flag { get; set; }
        public string statcond_map_dictname { get; set; }
        public string statcond_map_key_field { get; set; }
        public string statcond_map_list_field { get; set; }
    }
}
