//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hstatdata_conds
    {
        public int statdata_cond_id { get; set; }
        public string statrec_code { get; set; }
        public string statcond_code { get; set; }
        public string statcond_name { get; set; }
        public string statcond_fieldname { get; set; }
        public string statcond_fieldtype { get; set; }
        public string statcond_op { get; set; }
        public string statcond_value0 { get; set; }
        public string statcond_value1 { get; set; }
        public string statcond_result { get; set; }
        public string statcond_resdesc { get; set; }
    }
}
