//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hstatmethods
    {
        public string statmethod_code { get; set; }
        public string method_name { get; set; }
        public short dispseq { get; set; }
        public short method_runseq { get; set; }
        public bool method_mustflag { get; set; }
        public string depend_methods { get; set; }
        public Nullable<short> method_progtype { get; set; }
        public string method_progname { get; set; }
        public bool method_invalidflag { get; set; }
        public string method_params { get; set; }
        public string method_desc { get; set; }
    }
}
