//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hstatdatasets
    {
        public string statmethod_code { get; set; }
        public string statresult_code { get; set; }
        public bool DispVisible { get; set; }
        public short dispSeq { get; set; }
        public string DispCaption { get; set; }
        public string CallParams { get; set; }
        public string CallScript { get; set; }
    }
}
