//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hstatviews
    {
        public string statview_code { get; set; }
        public string statview_name { get; set; }
        public short statview_seq { get; set; }
        public string statview_desc { get; set; }
        public string sysid { get; set; }
        public string sysver { get; set; }
    }
}
