//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hstatdatasets
    {
        public string statmethod_code { get; set; }
        public string statresult_code { get; set; }
        public bool DispVisible { get; set; }
        public short dispSeq { get; set; }
        public string DispCaption { get; set; }
        public string CallParams { get; set; }
        public string CallScript { get; set; }
    }
}
