//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hstatdata_conds
    {
        public int statdata_cond_id { get; set; }
        public string statrec_code { get; set; }
        public string statcond_code { get; set; }
        public string statcond_name { get; set; }
        public string statcond_fieldname { get; set; }
        public string statcond_fieldtype { get; set; }
        public string statcond_op { get; set; }
        public string statcond_value0 { get; set; }
        public string statcond_value1 { get; set; }
        public string statcond_result { get; set; }
        public string statcond_resdesc { get; set; }
    }
}
