//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hstatreports
    {
        public string statmethod_code { get; set; }
        public string statreport_code { get; set; }
        public short dispseq { get; set; }
        public string DispCaption { get; set; }
        public string CallParams { get; set; }
        public byte[] rep_formdata { get; set; }
    }
}
