//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hstatdiags
    {
        public string statdiag_code { get; set; }
        public string p_statdiag_code { get; set; }
        public string statdiag_name { get; set; }
        public string statdiag_advice { get; set; }
        public bool invalidFlag { get; set; }
        public bool isTopFlag { get; set; }
        public bool isBottomFlag { get; set; }
        public int statdiag_seq { get; set; }
        public string statview_code { get; set; }
        public string vdiag_code { get; set; }
    }
}
