//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hstatconds
    {
        public string statcond_code { get; set; }
        public string statcond_name { get; set; }
        public string statcond_fieldname { get; set; }
        public string statcond_fieldtype { get; set; }
        public bool statcond_multflag { get; set; }
        public string statcond_desc { get; set; }
        public bool statcond_common_flag { get; set; }
        public string statcond_map_dictname { get; set; }
        public string statcond_map_key_field { get; set; }
        public string statcond_map_list_field { get; set; }
    }
}
