//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hstatdata_history_defines
    {
        public string statrec_code { get; set; }
        public string stathis_code { get; set; }
        public string stathis_name { get; set; }
        public Nullable<System.DateTime> stathis_begindate { get; set; }
        public Nullable<System.DateTime> stathis_enddate { get; set; }
    }
}
