//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class htaskacc
    {
        public string taskcode { get; set; }
        public string settletype { get; set; }
        public string settlecode { get; set; }
        public string settlename { get; set; }
        public System.DateTime settledate { get; set; }
        public Nullable<int> settleqty { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> stopdate { get; set; }
        public Nullable<decimal> checkfee { get; set; }
        public Nullable<decimal> undofee { get; set; }
        public Nullable<decimal> plusfee { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> sumfee { get; set; }
        public string invcode { get; set; }
        public string ifcard { get; set; }
        public string payall { get; set; }
        public string oper { get; set; }
        public string checkstatus { get; set; }
        public string remark { get; set; }
        public string plusmode { get; set; }
        public string b0110 { get; set; }
        public string workunit { get; set; }
        public string membcode { get; set; }
        public string a0107 { get; set; }
        public string age { get; set; }
        public string membtype { get; set; }
        public string ischecked { get; set; }
        public string taskseq { get; set; }
        public Nullable<decimal> pay1 { get; set; }
        public Nullable<decimal> pay2 { get; set; }
        public Nullable<decimal> pay3 { get; set; }
        public Nullable<decimal> pay4 { get; set; }
        public Nullable<decimal> pay5 { get; set; }
    }
}
