//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class htaskasmunion
    {
        public string gb2260 { get; set; }
        public string taskcode { get; set; }
        public string asmcode { get; set; }
        public string asmseq { get; set; }
        public string unioncode { get; set; }
        public string deptcode { get; set; }
        public string ifdel { get; set; }
        public string seq { get; set; }
        public string uniondesc { get; set; }
        public Nullable<decimal> unionfee { get; set; }
        public string remark { get; set; }
    }
}
