//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hTaskMembEx
    {
        public int identkey { get; set; }
        public string checkcode { get; set; }
        public string membcode { get; set; }
        public string taskcode { get; set; }
        public string taskseq { get; set; }
        public string settle_body { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
    }
}
