//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class htaskDepImage
    {
        public string gb2260 { get; set; }
        public string checkcode { get; set; }
        public string taskcode { get; set; }
        public string deptcode { get; set; }
        public string seq { get; set; }
        public string ifdel { get; set; }
        public Nullable<System.DateTime> checkdate { get; set; }
        public string sampleno { get; set; }
        public string ifpath { get; set; }
        public string imagepath { get; set; }
        public byte[] imagedata { get; set; }
        public string asmdesc { get; set; }
        public string tag { get; set; }
    }
}
