//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class htaskaccDetail
    {
        public string settlecode { get; set; }
        public string unioncode { get; set; }
        public string unionname { get; set; }
        public string feecode { get; set; }
        public Nullable<decimal> unionfee { get; set; }
        public string remark { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> unionfeeplus { get; set; }
        public Nullable<int> qtyplus { get; set; }
        public Nullable<decimal> unionfeeundo { get; set; }
        public Nullable<int> qtyundo { get; set; }
        public Nullable<decimal> discount { get; set; }
    }
}
