//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class htaskaccDetail
    {
        public string settlecode { get; set; }
        public string unioncode { get; set; }
        public string unionname { get; set; }
        public string feecode { get; set; }
        public Nullable<decimal> unionfee { get; set; }
        public string remark { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> unionfeeplus { get; set; }
        public Nullable<int> qtyplus { get; set; }
        public Nullable<decimal> unionfeeundo { get; set; }
        public Nullable<int> qtyundo { get; set; }
        public Nullable<decimal> discount { get; set; }
    }
}
