//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class htaskDeptest
    {
        public string gb2260 { get; set; }
        public string checkcode { get; set; }
        public string deptcode { get; set; }
        public string testcode { get; set; }
        public string wayid { get; set; }
        public string taskcode { get; set; }
        public string membcode { get; set; }
        public string unioncode { get; set; }
        public string htestcode { get; set; }
        public string testname { get; set; }
        public string testresult { get; set; }
        public string teststatus { get; set; }
        public string testsign { get; set; }
        public string testunit { get; set; }
        public string testrange { get; set; }
        public string testlower { get; set; }
        public string testhigher { get; set; }
        public string warncode { get; set; }
        public string remark { get; set; }
    }
}
