//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class htaskasm
    {
        public string taskcode { get; set; }
        public string gb2260 { get; set; }
        public string asmcode { get; set; }
        public string asmseq { get; set; }
        public string ifdel { get; set; }
        public string asmname { get; set; }
        public Nullable<decimal> asmfee { get; set; }
        public string asmsex { get; set; }
        public string asmdesc { get; set; }
        public string tag { get; set; }
        public Nullable<decimal> asmfeestd { get; set; }
        public string priasmcode { get; set; }
        public string priunionchg { get; set; }
        public Nullable<bool> ifstop { get; set; }
    }
}
