//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class htreetest
    {
        public string lev0 { get; set; }
        public string lev1 { get; set; }
        public string dictid { get; set; }
        public string dictcode { get; set; }
        public string dictcaption { get; set; }
        public string ifdel { get; set; }
        public string seq { get; set; }
        public string dictclass { get; set; }
        public string dictname { get; set; }
        public Nullable<short> dindex { get; set; }
        public string dictnote { get; set; }
        public string tag { get; set; }
    }
}
