//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class htreedict
    {
        public string lev0 { get; set; }
        public string lev1 { get; set; }
        public string dictid { get; set; }
        public string dictcode { get; set; }
        public string ifdel { get; set; }
        public string seq { get; set; }
        public string dictclass { get; set; }
        public string dictcaption { get; set; }
        public string dictname { get; set; }
        public Nullable<short> dindex { get; set; }
        public string dictnote { get; set; }
        public string tag { get; set; }
        public int identkey { get; set; }
    }
}
