//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hvirtualdiags
    {
        public string vdiag_code { get; set; }
        public string p_vdiag_code { get; set; }
        public int seq { get; set; }
        public string statsys_code { get; set; }
        public string vdiag_name { get; set; }
        public string vdiag_pycode { get; set; }
        public string vdiag_desc { get; set; }
        public string vdiag_advice { get; set; }
        public byte vdiag_sexflag { get; set; }
        public bool vdiag_bindflag { get; set; }
        public bool vdiag_stdflag { get; set; }
    }
}
