//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hvirtualdiags
    {
        public string vdiag_code { get; set; }
        public string p_vdiag_code { get; set; }
        public int seq { get; set; }
        public string statsys_code { get; set; }
        public string vdiag_name { get; set; }
        public string vdiag_pycode { get; set; }
        public string vdiag_desc { get; set; }
        public string vdiag_advice { get; set; }
        public byte vdiag_sexflag { get; set; }
        public bool vdiag_bindflag { get; set; }
        public bool vdiag_stdflag { get; set; }
    }
}
