//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class libicd10
    {
        public int icdkey { get; set; }
        public string idupdate { get; set; }
        public string idtodepart { get; set; }
        public Nullable<int> lev0 { get; set; }
        public string lev1 { get; set; }
        public string lev2 { get; set; }
        public string lev3 { get; set; }
        public string lev4 { get; set; }
        public Nullable<int> levtree { get; set; }
        public string icdclass { get; set; }
        public string icdcode { get; set; }
        public string icdcodea { get; set; }
        public string icdcname { get; set; }
        public string icdename { get; set; }
        public string icdpyt { get; set; }
        public string icdother { get; set; }
        public Nullable<System.DateTime> updateday { get; set; }
        public string updateoper { get; set; }
        public string icdnote { get; set; }
        public string code { get; set; }
        public string tag { get; set; }
    }
}
