//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class libsnomedother
    {
        public int snmkey { get; set; }
        public string idupdate { get; set; }
        public string termcode { get; set; }
        public string termchar { get; set; }
        public string cnomen { get; set; }
        public string enomen { get; set; }
        public string en50 { get; set; }
        public string modifer { get; set; }
        public string n { get; set; }
        public string @class { get; set; }
        public string q { get; set; }
        public string icdclass { get; set; }
        public string ahfs { get; set; }
        public string mfg { get; set; }
        public string iub { get; set; }
        public string icdref { get; set; }
        public string py_code { get; set; }
        public string wb_code { get; set; }
        public string referances { get; set; }
        public Nullable<System.DateTime> updateday { get; set; }
        public string updateoper { get; set; }
        public string icdnote { get; set; }
        public string tag { get; set; }
    }
}
