//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class medbaseEntities : DbContext
    {
        public medbaseEntities()
            : base("name=medbaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dtproperties> dtproperties { get; set; }
        public virtual DbSet<hactdepdiag> hactdepdiag { get; set; }
        public virtual DbSet<hactdiag> hactdiag { get; set; }
        public virtual DbSet<hactmemb> hactmemb { get; set; }
        public virtual DbSet<hactrep> hactrep { get; set; }
        public virtual DbSet<hacttest> hacttest { get; set; }
        public virtual DbSet<haudit> haudit { get; set; }
        public virtual DbSet<hbasegrp> hbasegrp { get; set; }
        public virtual DbSet<hbasegrpdept> hbasegrpdept { get; set; }
        public virtual DbSet<hbasegrpedit> hbasegrpedit { get; set; }
        public virtual DbSet<hbasememb> hbasememb { get; set; }
        public virtual DbSet<hbasemembcommon> hbasemembcommon { get; set; }
        public virtual DbSet<hbasemembdiag> hbasemembdiag { get; set; }
        public virtual DbSet<hbasemembrep> hbasemembrep { get; set; }
        public virtual DbSet<hbasemembunion> hbasemembunion { get; set; }
        public virtual DbSet<hcheckmemb> hcheckmemb { get; set; }
        public virtual DbSet<hdatadep> hdatadep { get; set; }
        public virtual DbSet<hdatadepdiag> hdatadepdiag { get; set; }
        public virtual DbSet<hdatadeptest> hdatadeptest { get; set; }
        public virtual DbSet<hdatadepunion> hdatadepunion { get; set; }
        public virtual DbSet<hdatadiag> hdatadiag { get; set; }
        public virtual DbSet<hdataimg> hdataimg { get; set; }
        public virtual DbSet<hdatarep> hdatarep { get; set; }
        public virtual DbSet<hError> hError { get; set; }
        public virtual DbSet<hknowdiag> hknowdiag { get; set; }
        public virtual DbSet<hknowtest> hknowtest { get; set; }
        public virtual DbSet<hknowunion> hknowunion { get; set; }
        public virtual DbSet<hlibasm> hlibasm { get; set; }
        public virtual DbSet<hlibdiag> hlibdiag { get; set; }
        public virtual DbSet<hlibpis> hlibpis { get; set; }
        public virtual DbSet<hlibpisform> hlibpisform { get; set; }
        public virtual DbSet<hlibrepform> hlibrepform { get; set; }
        public virtual DbSet<hlibtest> hlibtest { get; set; }
        public virtual DbSet<hlibtestattr> hlibtestattr { get; set; }
        public virtual DbSet<hlibtestdict> hlibtestdict { get; set; }
        public virtual DbSet<hlibtestops> hlibtestops { get; set; }
        public virtual DbSet<hlibuniontest> hlibuniontest { get; set; }
        public virtual DbSet<hlogdata> hlogdata { get; set; }
        public virtual DbSet<htask> htask { get; set; }
        public virtual DbSet<htaskacc> htaskacc { get; set; }
        public virtual DbSet<htaskaccDetail> htaskaccDetail { get; set; }
        public virtual DbSet<htaskasm> htaskasm { get; set; }
        public virtual DbSet<htaskasmunion> htaskasmunion { get; set; }
        public virtual DbSet<htaskdep> htaskdep { get; set; }
        public virtual DbSet<htaskdepdiag> htaskdepdiag { get; set; }
        public virtual DbSet<htaskDepImage> htaskDepImage { get; set; }
        public virtual DbSet<htaskdepunion> htaskdepunion { get; set; }
        public virtual DbSet<htaskdiag> htaskdiag { get; set; }
        public virtual DbSet<htaskgrp> htaskgrp { get; set; }
        public virtual DbSet<htaskimg> htaskimg { get; set; }
        public virtual DbSet<htaskmemb> htaskmemb { get; set; }
        public virtual DbSet<htaskrep> htaskrep { get; set; }
        public virtual DbSet<htreedict> htreedict { get; set; }
        public virtual DbSet<htreetest> htreetest { get; set; }
        public virtual DbSet<libicd10> libicd10 { get; set; }
        public virtual DbSet<libsnomed> libsnomed { get; set; }
        public virtual DbSet<ycheckmemb> ycheckmemb { get; set; }
        public virtual DbSet<ytask> ytask { get; set; }
        public virtual DbSet<ytaskacc> ytaskacc { get; set; }
        public virtual DbSet<ytaskaccDetail> ytaskaccDetail { get; set; }
        public virtual DbSet<ytaskasm> ytaskasm { get; set; }
        public virtual DbSet<ytaskasmunion> ytaskasmunion { get; set; }
        public virtual DbSet<ytaskdep> ytaskdep { get; set; }
        public virtual DbSet<ytaskdepdiag> ytaskdepdiag { get; set; }
        public virtual DbSet<ytaskdepunion> ytaskdepunion { get; set; }
        public virtual DbSet<ytaskdiag> ytaskdiag { get; set; }
        public virtual DbSet<ytaskgrp> ytaskgrp { get; set; }
        public virtual DbSet<ytaskimg> ytaskimg { get; set; }
        public virtual DbSet<ytaskmemb> ytaskmemb { get; set; }
        public virtual DbSet<ytaskrep> ytaskrep { get; set; }
        public virtual DbSet<hbasemembedit> hbasemembedit { get; set; }
        public virtual DbSet<hlibdept> hlibdept { get; set; }
        public virtual DbSet<hlibuniondiag> hlibuniondiag { get; set; }
        public virtual DbSet<hstat_result_data> hstat_result_data { get; set; }
        public virtual DbSet<hstat_result_data_namelist> hstat_result_data_namelist { get; set; }
        public virtual DbSet<hstat_sessions> hstat_sessions { get; set; }
        public virtual DbSet<hstatcharts> hstatcharts { get; set; }
        public virtual DbSet<hstatconds> hstatconds { get; set; }
        public virtual DbSet<hstatdata_conds> hstatdata_conds { get; set; }
        public virtual DbSet<hstatdata_history_defines> hstatdata_history_defines { get; set; }
        public virtual DbSet<hstatdata_methods> hstatdata_methods { get; set; }
        public virtual DbSet<hstatdata_views> hstatdata_views { get; set; }
        public virtual DbSet<hstatdatasets> hstatdatasets { get; set; }
        public virtual DbSet<hstatdiags> hstatdiags { get; set; }
        public virtual DbSet<hstatmainrec> hstatmainrec { get; set; }
        public virtual DbSet<hstatmethods> hstatmethods { get; set; }
        public virtual DbSet<hstatreports> hstatreports { get; set; }
        public virtual DbSet<hstatviews> hstatviews { get; set; }
        public virtual DbSet<htaskasmtest> htaskasmtest { get; set; }
        public virtual DbSet<htaskDeptest> htaskDeptest { get; set; }
        public virtual DbSet<htaskdiagpost> htaskdiagpost { get; set; }
        public virtual DbSet<hvirtualdiags> hvirtualdiags { get; set; }
        public virtual DbSet<libicd10zj> libicd10zj { get; set; }
        public virtual DbSet<libsnomedother> libsnomedother { get; set; }
        public virtual DbSet<pbcatcol> pbcatcol { get; set; }
        public virtual DbSet<pbcatedt> pbcatedt { get; set; }
        public virtual DbSet<pbcatfmt> pbcatfmt { get; set; }
        public virtual DbSet<pbcattbl> pbcattbl { get; set; }
        public virtual DbSet<pbcatvld> pbcatvld { get; set; }
        public virtual DbSet<pisform> pisform { get; set; }
        public virtual DbSet<tj2> tj2 { get; set; }
        public virtual DbSet<tj2_backup> tj2_backup { get; set; }
        public virtual DbSet<tj2_backup2> tj2_backup2 { get; set; }
        public virtual DbSet<tj2_backup3> tj2_backup3 { get; set; }
        public virtual DbSet<tj2_deleted> tj2_deleted { get; set; }
        public virtual DbSet<x1> x1 { get; set; }
        public virtual DbSet<x11> x11 { get; set; }
        public virtual DbSet<x2> x2 { get; set; }
        public virtual DbSet<x22> x22 { get; set; }
        public virtual DbSet<ytaskDeptest> ytaskDeptest { get; set; }
    }
}
