//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class medbase201507Entities1 : DbContext
    {
        public medbase201507Entities1()
            : base("name=medbase201507Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_dict_manager> C_dict_manager { get; set; }
        public virtual DbSet<C_dict_tbcode> C_dict_tbcode { get; set; }
        public virtual DbSet<C_dict_tbdiscountRates> C_dict_tbdiscountRates { get; set; }
        public virtual DbSet<C_dict_tbhtestcode> C_dict_tbhtestcode { get; set; }
        public virtual DbSet<C_dict_tbinterface> C_dict_tbinterface { get; set; }
        public virtual DbSet<C_dict_tbinterface_event> C_dict_tbinterface_event { get; set; }
        public virtual DbSet<C_dict_tbsalesman> C_dict_tbsalesman { get; set; }
        public virtual DbSet<C_result_htaskacc_detail> C_result_htaskacc_detail { get; set; }
        public virtual DbSet<C_sdsl_StatResult> C_sdsl_StatResult { get; set; }
        public virtual DbSet<C_sdsl_statTest> C_sdsl_statTest { get; set; }
        public virtual DbSet<CollectedInfoTable> CollectedInfoTable { get; set; }
        public virtual DbSet<discountRates_task> discountRates_task { get; set; }
        public virtual DbSet<discountRates_task_union> discountRates_task_union { get; set; }
        public virtual DbSet<dtproperties> dtproperties { get; set; }
        public virtual DbSet<hactdep> hactdep { get; set; }
        public virtual DbSet<hactdepdiag> hactdepdiag { get; set; }
        public virtual DbSet<hactdepunion> hactdepunion { get; set; }
        public virtual DbSet<hactdiag> hactdiag { get; set; }
        public virtual DbSet<hactmemb> hactmemb { get; set; }
        public virtual DbSet<hactrep> hactrep { get; set; }
        public virtual DbSet<hacttest> hacttest { get; set; }
        public virtual DbSet<haudit> haudit { get; set; }
        public virtual DbSet<hbasegrp> hbasegrp { get; set; }
        public virtual DbSet<hbasegrpdept> hbasegrpdept { get; set; }
        public virtual DbSet<hbasegrpedit> hbasegrpedit { get; set; }
        public virtual DbSet<hbasememb> hbasememb { get; set; }
        public virtual DbSet<hbasemembcommon> hbasemembcommon { get; set; }
        public virtual DbSet<hbasemembdiag> hbasemembdiag { get; set; }
        public virtual DbSet<hbasemembedit> hbasemembedit { get; set; }
        public virtual DbSet<hbasemembrep> hbasemembrep { get; set; }
        public virtual DbSet<hbasemembunion> hbasemembunion { get; set; }
        public virtual DbSet<hcheckmemb> hcheckmemb { get; set; }
        public virtual DbSet<hdatadep> hdatadep { get; set; }
        public virtual DbSet<hdatadepdiag> hdatadepdiag { get; set; }
        public virtual DbSet<hdatadeptest> hdatadeptest { get; set; }
        public virtual DbSet<hdatadepunion> hdatadepunion { get; set; }
        public virtual DbSet<hdatadiag> hdatadiag { get; set; }
        public virtual DbSet<hdataimg> hdataimg { get; set; }
        public virtual DbSet<hdatarep> hdatarep { get; set; }
        public virtual DbSet<hError> hError { get; set; }
        public virtual DbSet<hknowdiag> hknowdiag { get; set; }
        public virtual DbSet<hknowtest> hknowtest { get; set; }
        public virtual DbSet<hknowunion> hknowunion { get; set; }
        public virtual DbSet<hlibasm> hlibasm { get; set; }
        public virtual DbSet<hlibdiag> hlibdiag { get; set; }
        public virtual DbSet<hlibpis> hlibpis { get; set; }
        public virtual DbSet<hlibpisform> hlibpisform { get; set; }
        public virtual DbSet<hlibrepform> hlibrepform { get; set; }
        public virtual DbSet<hlibtest> hlibtest { get; set; }
        public virtual DbSet<hlibtestattr> hlibtestattr { get; set; }
        public virtual DbSet<hlibtestdict> hlibtestdict { get; set; }
        public virtual DbSet<hlibtestops> hlibtestops { get; set; }
        public virtual DbSet<hlibuniontest> hlibuniontest { get; set; }
        public virtual DbSet<hlogdata> hlogdata { get; set; }
        public virtual DbSet<hpaidrec> hpaidrec { get; set; }
        public virtual DbSet<hpaidrec_details> hpaidrec_details { get; set; }
        public virtual DbSet<hstat_sessions> hstat_sessions { get; set; }
        public virtual DbSet<hstatcharts> hstatcharts { get; set; }
        public virtual DbSet<hstatconds> hstatconds { get; set; }
        public virtual DbSet<hstatdata_conds> hstatdata_conds { get; set; }
        public virtual DbSet<hstatdata_methods> hstatdata_methods { get; set; }
        public virtual DbSet<hstatdata_views> hstatdata_views { get; set; }
        public virtual DbSet<hstatdatasets> hstatdatasets { get; set; }
        public virtual DbSet<hstatdiags> hstatdiags { get; set; }
        public virtual DbSet<hstatmainrec> hstatmainrec { get; set; }
        public virtual DbSet<hstatmethods> hstatmethods { get; set; }
        public virtual DbSet<hstatreports> hstatreports { get; set; }
        public virtual DbSet<hstatviews> hstatviews { get; set; }
        public virtual DbSet<htask> htask { get; set; }
        public virtual DbSet<htaskacc> htaskacc { get; set; }
        public virtual DbSet<htaskaccDetail> htaskaccDetail { get; set; }
        public virtual DbSet<htaskasm> htaskasm { get; set; }
        public virtual DbSet<htaskasmunion> htaskasmunion { get; set; }
        public virtual DbSet<htaskdep> htaskdep { get; set; }
        public virtual DbSet<htaskdepdiag> htaskdepdiag { get; set; }
        public virtual DbSet<htaskDepImage> htaskDepImage { get; set; }
        public virtual DbSet<htaskdepunion> htaskdepunion { get; set; }
        public virtual DbSet<htaskdiag> htaskdiag { get; set; }
        public virtual DbSet<htaskgrp> htaskgrp { get; set; }
        public virtual DbSet<htaskimg> htaskimg { get; set; }
        public virtual DbSet<htaskmemb> htaskmemb { get; set; }
        public virtual DbSet<hTaskMembEx> hTaskMembEx { get; set; }
        public virtual DbSet<hTaskMembImp> hTaskMembImp { get; set; }
        public virtual DbSet<htaskrep> htaskrep { get; set; }
        public virtual DbSet<htaskunionfee> htaskunionfee { get; set; }
        public virtual DbSet<htreedict> htreedict { get; set; }
        public virtual DbSet<htreetest> htreetest { get; set; }
        public virtual DbSet<hvirtualdiags> hvirtualdiags { get; set; }
        public virtual DbSet<libicd10> libicd10 { get; set; }
        public virtual DbSet<libsnomed> libsnomed { get; set; }
        public virtual DbSet<pisuser> pisuser { get; set; }
        public virtual DbSet<ycheckmemb> ycheckmemb { get; set; }
        public virtual DbSet<ytask> ytask { get; set; }
        public virtual DbSet<ytaskacc> ytaskacc { get; set; }
        public virtual DbSet<ytaskaccDetail> ytaskaccDetail { get; set; }
        public virtual DbSet<ytaskasm> ytaskasm { get; set; }
        public virtual DbSet<ytaskasmunion> ytaskasmunion { get; set; }
        public virtual DbSet<ytaskdep> ytaskdep { get; set; }
        public virtual DbSet<ytaskdepdiag> ytaskdepdiag { get; set; }
        public virtual DbSet<ytaskDeptest> ytaskDeptest { get; set; }
        public virtual DbSet<ytaskdepunion> ytaskdepunion { get; set; }
        public virtual DbSet<ytaskdiag> ytaskdiag { get; set; }
        public virtual DbSet<ytaskgrp> ytaskgrp { get; set; }
        public virtual DbSet<ytaskimg> ytaskimg { get; set; }
        public virtual DbSet<ytaskmemb> ytaskmemb { get; set; }
        public virtual DbSet<ytaskrep> ytaskrep { get; set; }
        public virtual DbSet<hlibdept> hlibdept { get; set; }
        public virtual DbSet<hlibuniondiag> hlibuniondiag { get; set; }
        public virtual DbSet<hstat_result_data> hstat_result_data { get; set; }
        public virtual DbSet<hstat_result_data_namelist> hstat_result_data_namelist { get; set; }
        public virtual DbSet<hstatdata_history_defines> hstatdata_history_defines { get; set; }
        public virtual DbSet<htaskasmtest> htaskasmtest { get; set; }
        public virtual DbSet<htaskDeptest> htaskDeptest { get; set; }
        public virtual DbSet<libsnomedother> libsnomedother { get; set; }
        public virtual DbSet<pbcatcol> pbcatcol { get; set; }
        public virtual DbSet<pbcatedt> pbcatedt { get; set; }
        public virtual DbSet<pbcatfmt> pbcatfmt { get; set; }
        public virtual DbSet<pbcattbl> pbcattbl { get; set; }
        public virtual DbSet<pbcatvld> pbcatvld { get; set; }
        public virtual DbSet<pisform> pisform { get; set; }
    }
}
