//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class pbcattbl
    {
        public string pbt_tnam { get; set; }
        public Nullable<int> pbt_tid { get; set; }
        public string pbt_ownr { get; set; }
        public Nullable<short> pbd_fhgt { get; set; }
        public Nullable<short> pbd_fwgt { get; set; }
        public string pbd_fitl { get; set; }
        public string pbd_funl { get; set; }
        public Nullable<short> pbd_fchr { get; set; }
        public Nullable<short> pbd_fptc { get; set; }
        public string pbd_ffce { get; set; }
        public Nullable<short> pbh_fhgt { get; set; }
        public Nullable<short> pbh_fwgt { get; set; }
        public string pbh_fitl { get; set; }
        public string pbh_funl { get; set; }
        public Nullable<short> pbh_fchr { get; set; }
        public Nullable<short> pbh_fptc { get; set; }
        public string pbh_ffce { get; set; }
        public Nullable<short> pbl_fhgt { get; set; }
        public Nullable<short> pbl_fwgt { get; set; }
        public string pbl_fitl { get; set; }
        public string pbl_funl { get; set; }
        public Nullable<short> pbl_fchr { get; set; }
        public Nullable<short> pbl_fptc { get; set; }
        public string pbl_ffce { get; set; }
        public string pbt_cmnt { get; set; }
    }
}
