//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class pbcatfmt
    {
        public string pbf_name { get; set; }
        public string pbf_frmt { get; set; }
        public Nullable<short> pbf_type { get; set; }
        public Nullable<int> pbf_cntr { get; set; }
    }
}
