//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class pbcatedt
    {
        public string pbe_name { get; set; }
        public string pbe_edit { get; set; }
        public Nullable<short> pbe_type { get; set; }
        public Nullable<int> pbe_cntr { get; set; }
        public short pbe_seqn { get; set; }
        public Nullable<int> pbe_flag { get; set; }
        public string pbe_work { get; set; }
    }
}
