//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class pbcatcol
    {
        public string pbc_tnam { get; set; }
        public Nullable<int> pbc_tid { get; set; }
        public string pbc_ownr { get; set; }
        public string pbc_cnam { get; set; }
        public Nullable<short> pbc_cid { get; set; }
        public string pbc_labl { get; set; }
        public Nullable<short> pbc_lpos { get; set; }
        public string pbc_hdr { get; set; }
        public Nullable<short> pbc_hpos { get; set; }
        public Nullable<short> pbc_jtfy { get; set; }
        public string pbc_mask { get; set; }
        public Nullable<short> pbc_case { get; set; }
        public Nullable<short> pbc_hght { get; set; }
        public Nullable<short> pbc_wdth { get; set; }
        public string pbc_ptrn { get; set; }
        public string pbc_bmap { get; set; }
        public string pbc_init { get; set; }
        public string pbc_cmnt { get; set; }
        public string pbc_edit { get; set; }
        public string pbc_tag { get; set; }
    }
}
