//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class pisform
    {
        public Nullable<short> ifdel { get; set; }
        public Nullable<short> ifactive { get; set; }
        public Nullable<short> ifsign { get; set; }
        public Nullable<short> ifdetail { get; set; }
        public string deptcode { get; set; }
        public Nullable<int> seq { get; set; }
        public string testcode { get; set; }
        public string signcode { get; set; }
        public string signtype { get; set; }
        public string signname { get; set; }
        public string diagview { get; set; }
        public string testresult { get; set; }
        public string signadvice { get; set; }
        public string diagviewform { get; set; }
        public string diagwhere { get; set; }
        public string diagdegree { get; set; }
        public string diagclass { get; set; }
        public string hiscode { get; set; }
        public string his { get; set; }
        public string oper { get; set; }
        public Nullable<System.DateTime> operdate { get; set; }
        public string sysid { get; set; }
        public string syscode { get; set; }
        public string sysver { get; set; }
        public string remark { get; set; }
        public Nullable<int> tag { get; set; }
        public int identkey { get; set; }
    }
}
