//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class pisform
    {
        public Nullable<short> ifdel { get; set; }
        public Nullable<short> ifactive { get; set; }
        public Nullable<short> ifsign { get; set; }
        public Nullable<short> ifdetail { get; set; }
        public string deptcode { get; set; }
        public Nullable<int> seq { get; set; }
        public string testcode { get; set; }
        public string signcode { get; set; }
        public string signtype { get; set; }
        public string signname { get; set; }
        public string diagview { get; set; }
        public string testresult { get; set; }
        public string signadvice { get; set; }
        public string diagviewform { get; set; }
        public string diagwhere { get; set; }
        public string diagdegree { get; set; }
        public string diagclass { get; set; }
        public string hiscode { get; set; }
        public string his { get; set; }
        public string oper { get; set; }
        public Nullable<System.DateTime> operdate { get; set; }
        public string sysid { get; set; }
        public string syscode { get; set; }
        public string sysver { get; set; }
        public string remark { get; set; }
        public Nullable<int> tag { get; set; }
    }
}
