//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tj2_backup
    {
        public string signcode { get; set; }
        public string diagname { get; set; }
        public string signtype { get; set; }
        public Nullable<int> sum_count { get; set; }
        public string diagdept { get; set; }
        public string patlist { get; set; }
        public Nullable<short> visible_flag { get; set; }
        public Nullable<short> del_flag { get; set; }
        public string merge_str { get; set; }
    }
}
