//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class x1
    {
        public string usercode { get; set; }
        public string deptcode { get; set; }
        public int deptseq { get; set; }
        public string htestcode { get; set; }
        public string signcode { get; set; }
        public string signname { get; set; }
        public string signadvice { get; set; }
        public string pycode { get; set; }
        public int signusage { get; set; }
        public int ifdetail { get; set; }
        public string his { get; set; }
        public string oper { get; set; }
        public Nullable<System.DateTime> operdate { get; set; }
    }
}
