//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ytaskmemb
    {
        public string gb2260 { get; set; }
        public string taskcode { get; set; }
        public string taskseq { get; set; }
        public string membtype { get; set; }
        public string membcode { get; set; }
        public string membclasscode { get; set; }
        public string ifdel { get; set; }
        public string ifcard { get; set; }
        public string a0177 { get; set; }
        public string a0101 { get; set; }
        public string a0107 { get; set; }
        public string age { get; set; }
        public Nullable<System.DateTime> a0111 { get; set; }
        public string a0405 { get; set; }
        public string a2205 { get; set; }
        public string a0704 { get; set; }
        public string a0724 { get; set; }
        public Nullable<System.DateTime> a0707 { get; set; }
        public string a6405 { get; set; }
        public Nullable<System.DateTime> a6410 { get; set; }
        public string a0127 { get; set; }
        public string tel { get; set; }
        public string workunit { get; set; }
        public string b0110 { get; set; }
        public string b0105 { get; set; }
        public string asmcode { get; set; }
        public string asmseq { get; set; }
        public Nullable<decimal> asmfee { get; set; }
        public string ifasmdep { get; set; }
        public string asmdepstr { get; set; }
        public string taskrunid { get; set; }
        public Nullable<System.DateTime> checkdate { get; set; }
        public string ifhide { get; set; }
        public string hiscode { get; set; }
        public string iftrace { get; set; }
        public string tracereason { get; set; }
        public string tracenote { get; set; }
        public string tracer { get; set; }
        public Nullable<System.DateTime> tracedate { get; set; }
        public string remark { get; set; }
        public string asmdesc { get; set; }
        public string ifsettle { get; set; }
        public string pis_01 { get; set; }
        public string medicareno { get; set; }
        public string duty { get; set; }
        public string healthcode { get; set; }
        public string mobileno { get; set; }
        public string a0101x { get; set; }
        public string a8210 { get; set; }
        public string a8215 { get; set; }
        public string email { get; set; }
        public string tasktype { get; set; }
        public string settlecode { get; set; }
        public string ifsend { get; set; }
    }
}
