//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ytaskrep
    {
        public string gb2260 { get; set; }
        public string checkcode { get; set; }
        public string taskcode { get; set; }
        public string seq { get; set; }
        public string membcode { get; set; }
        public string membtype { get; set; }
        public Nullable<System.DateTime> initday { get; set; }
        public string checkstatus { get; set; }
        public string iffinished { get; set; }
        public string iflock { get; set; }
        public string hresult { get; set; }
        public string hresultother { get; set; }
        public string hadvice { get; set; }
        public string checkdoc { get; set; }
        public string reviewdoc { get; set; }
        public Nullable<System.DateTime> checkdate { get; set; }
        public string remark { get; set; }
        public string workunit { get; set; }
        public string iftrace { get; set; }
        public string ifprint { get; set; }
        public string ifad { get; set; }
        public string adclass { get; set; }
        public Nullable<System.DateTime> archivedate { get; set; }
        public Nullable<System.DateTime> printdate { get; set; }
    }
}
