//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ytaskdepunion
    {
        public string gb2260 { get; set; }
        public string checkcode { get; set; }
        public string deptcode { get; set; }
        public string unioncode { get; set; }
        public string taskcode { get; set; }
        public string seq { get; set; }
        public string membcode { get; set; }
        public string membtype { get; set; }
        public Nullable<System.DateTime> initday { get; set; }
        public string checkstatus { get; set; }
        public string sampleno { get; set; }
        public string depresult { get; set; }
        public Nullable<System.DateTime> checkdate { get; set; }
        public string checkdoc { get; set; }
        public string reviewdoc { get; set; }
        public string iffinished { get; set; }
        public string iflock { get; set; }
        public string ifdata { get; set; }
        public string testsignstr { get; set; }
        public Nullable<decimal> unionfee { get; set; }
        public string ifplus { get; set; }
        public string tag { get; set; }
        public string ifsettle { get; set; }
        public string rackno { get; set; }
        public string rackoper { get; set; }
        public string racktime { get; set; }
        public string uname { get; set; }
        public short deptseq { get; set; }
        public string work { get; set; }
        public Nullable<short> rackbatch { get; set; }
        public string uniondesc { get; set; }
        public Nullable<short> regstatus { get; set; }
        public string checklevel { get; set; }
        public string settlecode { get; set; }
    }
}
