//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ytaskasmunion
    {
        public string gb2260 { get; set; }
        public string taskcode { get; set; }
        public string asmcode { get; set; }
        public string asmseq { get; set; }
        public string unioncode { get; set; }
        public string deptcode { get; set; }
        public string ifdel { get; set; }
        public string seq { get; set; }
        public string uniondesc { get; set; }
        public Nullable<decimal> unionfee { get; set; }
        public string remark { get; set; }
    }
}
