//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ytaskDeptest
    {
        public string gb2260 { get; set; }
        public string checkcode { get; set; }
        public string deptcode { get; set; }
        public string testcode { get; set; }
        public string wayid { get; set; }
        public string taskcode { get; set; }
        public string membcode { get; set; }
        public string unioncode { get; set; }
        public string htestcode { get; set; }
        public string testname { get; set; }
        public string testresult { get; set; }
        public string teststatus { get; set; }
        public string testsign { get; set; }
        public string testunit { get; set; }
        public string testrange { get; set; }
        public string testlower { get; set; }
        public string testhigher { get; set; }
        public string warncode { get; set; }
        public string remark { get; set; }
    }
}
