//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ytaskrep
    {
        public string gb2260 { get; set; }
        public string checkcode { get; set; }
        public string taskcode { get; set; }
        public string seq { get; set; }
        public string membcode { get; set; }
        public string membtype { get; set; }
        public Nullable<System.DateTime> initday { get; set; }
        public string checkstatus { get; set; }
        public string iffinished { get; set; }
        public string iflock { get; set; }
        public string hresult { get; set; }
        public string hresultother { get; set; }
        public string hadvice { get; set; }
        public string checkdoc { get; set; }
        public string reviewdoc { get; set; }
        public Nullable<System.DateTime> checkdate { get; set; }
        public string remark { get; set; }
        public string workunit { get; set; }
        public Nullable<short> ifad { get; set; }
        public string adclass { get; set; }
        public string iftrace { get; set; }
        public string ifprint { get; set; }
    }
}
