//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataExport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ytaskgrp
    {
        public string gb2260 { get; set; }
        public string taskcode { get; set; }
        public string b0110 { get; set; }
        public string b0105 { get; set; }
        public string ifdel { get; set; }
        public string b0160 { get; set; }
        public string b0150 { get; set; }
        public string b0170 { get; set; }
        public string remark { get; set; }
    }
}
